# Generated by Django 4.1.1 on 2024-09-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('offered_car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.car')),
            ],
        ),
    ]
