# Generated by Django 4.1 on 2024-10-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_carfeature_car_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.car')),
            ],
        ),
    ]
